# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
dist: trusty

r:
  - oldrel
  - release
  - bioc-release
  - bioc-devel

bioc_required: true

r_packages:
  - knitr
  - XML
  - plyr
  - doParallel
  - foreach
  - iterators


 r_github_packages:
  - r-lib/covr 

bioc_packages: 
  - xcms 
  - Rgraphviz
  - MSnbase
  - CAMERA
  - mzR
  
apt_packages:
  - texlive-latex-extra
  - texlive-fonts-extra
  - texlive-latex-recommended
  - libnetcdf-dev
  - netcdf-bin
  - libhdf5-dev
  - libxml2-dev #for XML...
